### PR TITLE
--- applications: - name: spring-petclinic   memory: 512M   instances…

### PR DESCRIPTION
**Pull request by KumareshBabuNS**
…: 1   random-route: true   path: build/libs/spring-petclinic.war

### CODE REVIEW

**Comment by arey** [comment]
I think it's a mistake

**Comment by KumareshBabuNS** [comment]
Hi Arey,
Thanks for reply.
What's the mistake?

**Comment by arey** [comment]
Pull Request title and comments are not very explicit.
But I found a manifest.yml enables to deploy Petclinic into Cloud Foundry. Isn't it?

**Comment by KumareshBabuNS** [comment]
Yes

**Comment by KumareshBabuNS** [comment]
In manifest.yml file, remove the path attribute. Given path attribute value is invalid.

**Pull request closed without merging**
