### PR TITLE
fix for patch #682

### PR DESCRIPTION
**Pull request by somayaj**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@somayaj Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=684)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=684) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@somayaj Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=684)!

**Review by somayaj — COMMENTED** [review]
Fix for patch # 682

**Comment by snicoll** [comment]
Thanks but I don't think the logic should be set in the UI but rather in the data itself.

**Comment by somayaj** [comment]
That's fine, thanks

**Pull request closed without merging**
