### PR TITLE
Adding support for Azure Spring Apps with PostgreSQL

### PR DESCRIPTION
**Pull request by nevenc**
Added support for deploying spring-petclinic to Azure Spring Apps using PostgreSQL.

### CODE REVIEW

**Comment by jaididon** [comment]
How to use file in intellij idea for Java spring boot??

**Comment by nevenc** [comment]
> How to use file in intellij idea for Java spring boot??

What do you mean @jaididon?
What file specifically?
What are you trying to do?

**Comment by jaididon** [comment]
File Specially
index.java

**Comment by jaididon** [comment]
I am trying to do coding of Java springboot
But I don't have a clue how to create index.java in intellij idea

**Comment by dsyer** [comment]
People should be able to use Petclinic on Azure without changing the source code. Maybe instead of a new properties file we could just add the comment about the JAVA_OPTS in the existing one? Or (better) in the txt file that lives near the SQL scripts?

**Pull request closed without merging**
