### PR TITLE
Modularize and migrate to aggregate-oriented domain

### PR DESCRIPTION
**Pull request by dsyer**
Vet, Owner, Visit. The Visit "aggregate" is a little artificial
but it demonstrates a useful point about not holding on to
references of "parent" (reference data) objects, i.e. the Visit has
an Integer petId, instead of a Pet field. In principle this app is
now almost ready to migrate to multiple services if anyone wanted
to do that.

### CODE REVIEW

**Comment by vfedoriv** [comment]
Hi.
As I see, you drop all service layer ?
IMHO, it's a not nice idea pull this in **master** branch.
Maybe, create new branch for microservices architecture ?

**Comment by mszarlinski** [comment]
Hi @vfedoriv I am currently working on a microservices version and I named the branch "spring-cloud". Please see discussion in #198

**Comment by dsyer** [comment]
Clarification: this is not a "microservice" conversion. This is just a modernization, using Spring Boot and a clear modular structure in a way that is more consistent with best practice in 2016, as opposed to 2003 when this app was first written.

**Comment by vfedoriv** [comment]
"best practice" in Java - legacy support  ;)

**Comment by vfedoriv** [comment]
Of course, you right. 
But half of this project "a little artificial". :)  How about model : BaseEntity -> NamedEntity ->... 
We really need this ?

**Comment by dsyer** [comment]
I agree those classes would have to be factored out or their features duplicated if you were to split it up into actual physical modules. My judgement is that this is a small enough task that I don't mind deferring it (probably it never need happen in this repo). Worth a comment in the README though.

**Comment by olivergierke** [comment]
Should the `VisitController` move into the `visit` package, too?

**Comment by dsyer** [comment]
It's part of the "owner" UI, and as such it depends on the `PetRepository`. So moving it to the visit package creates a tangle.

**Comment by olivergierke** [comment]
I wonder if it makes sense to invert the relationship between `Pet` and `Visit`. I'd argue managing pets and owners is useful on its own (a CRM like application). The notion of visits to the doctor is then coming on top of that. Owners and pets *without* visits makes sense. A visit without a pet — not so much.

`VisitRepository` sort of already works that way as it exposes a `findByPetId(…)`. This makes me feel like keeping the visits mapped on the `Pet` side is kind of obsolete and sort of breaking the abstraction direction.

So I'd rather make the visit an aggregate on it's own so that the `Visit` instances are created via the repository by being bound to a `Pet` (or it's identifier, I think even using `Pet` is fine here). That would allow us to move the URIs for view creation to the top level.

We could also go ahead and merge this as is so that we can create another PR with my suggested changes to see how that effects the structure of the codebase overall.

WDYT?

**Comment by dsyer** [comment]
I played with various combinations and discarded them, but I'm not sure if that was one of them. Incremental changes after a merge also makes sense, if there are no objections to the change in principle (seems not).

**Comment by olivergierke** [comment]
Okay, summarizing, I don't think anything in the proposed changes that really violates the fundamental goals of the ticket. So feel free to merge and I'll give it a spin on top for separate discussion.

**Comment by dsyer** [comment]
Merged 83ff9a5

**Pull request closed without merging**
