### PR TITLE
adding new message in Spanish

### PR DESCRIPTION
**Pull request by aleVeD**
Hello, how are you, I agree with the message part of an option in Spanish for messages, as it was in the course if you knew another language you could add it in messaje.properties

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@aleVeD Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=631)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=631) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@aleVeD Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=631)!

**Comment by dsyer** [comment]
LGTM (although I'm not sure we need all the languages - it's just a sample).

**Comment by aleVeD** [comment]
don't worry if they don't add it it's fine

**Comment by dsyer** [comment]
I decided to merge. Other contributors, please note: we don't need content for *all* languages (the source code for this app needs to stay weighted towards Java and Spring IMO - it's just to show you how to do it, so to be an actaul PetClinic). But if you have Chinese or Japanese or Korean, we could maybe squeak one of those in.

**Pull request merged**
