### PR TITLE
Downgrade to wro4j 1.8.0 as the latest version requires Java 11

### PR DESCRIPTION
**Pull request by Arka-Bandyopadhyay**
leave .vscode folder out of project for at least master branch as it IDE specific configuration , or else create vscode specific branch, so that it remains ide's agnostic.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Arka-Bandyopadhyay Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=707)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=707) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Arka-Bandyopadhyay Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=707)!

**Comment by Arka-Bandyopadhyay** [comment]
Added fixed build failed issue to latest wro4jmojo plugin version

**Comment by snicoll** [comment]
Thank you for the PR but a commit should focus on one task and one task only. I agree that the project should not have IDE specific configuration so I've fixed that in https://github.com/spring-projects/spring-petclinic/commit/502870d6c031692b2111602a3eae5ae00e24efd9. Let's use this PR to handle the wro4j problem.

**Comment by snicoll** [comment]
@Arka-Bandyopadhyay thank you for making your first contribution to Spring Petclinic. Note that we may increase the minimal requirements of this project to Java 11 in the near future so I invite  you to upgrade your Java runtime regardless.

**Pull request closed without merging**
