### PR TITLE
remove trailing slash

### PR DESCRIPTION
**Pull request by bluehoped**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bluehoped Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=616)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=616) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@bluehoped Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=616)!

**Comment by bluehoped** [comment]
Thank you too.
@pivotal-issuemaster 
I will come back after studying English :)

**Comment by dsyer** [comment]
Good catch. Thanks.

**Pull request merged**
