### PR TITLE
Attempt to migrate maven pom.xml to gradle #236

### PR DESCRIPTION
**Pull request by bgalek**
less mixins not working ;(
but tests are passing, build seems ok, if you want me to continue - just say a word ;)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bgalek Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=365)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=365) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@bgalek Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=365)!

**Comment by dsyer** [comment]
I commented on the commit.

**Comment by dsyer** [comment]
The intention on #236 was not to remove Maven. Just to provide a way for gradle users to play with the project.

**Comment by bgalek** [comment]
@dsyer That's a fast feedback loop! thanks!
I can make it work without removing maven support of course - are you willing to maintain both gradle and pom.xml files? :)

**Comment by dsyer** [comment]
>  are you willing to maintain both gradle and pom.xml files? :)

Up to a point. If the build.gradle it's broken and I can't fix it I will ask for help. Your name will be top of the list.

**Comment by dsyer** [comment]
Duplicates #385. Neither is mergeable though.

**Comment by Lewiscowles1986** [comment]
https://github.com/spring-projects/spring-petclinic/pull/385 now seems to be the PR to track. Not much movement since April, but given the review comments I can't blame them

**Pull request closed without merging**
