### PR TITLE
Feature/integtration test

### LINKED ISSUE #692: Implement integration tests
I want to add severals unit and  integrations test to improve the code.
It's better to add IT in the java test file name and run them in verify lifecycle.

### PR DESCRIPTION
**Pull request by pedsf1968**
#End of feature Integration Test
ISSUE #692 
Base on merge request #687 with Services and DTOs
- Implement integration tests for controllers
- Update unitaries tests
- Make sommes corrections
- Modify .travis with two steps Maven test and Maven verify

close #692

### CODE REVIEW

**Comment by pedsf1968** [comment]
@snicoll this project is it stuck? It seems that no new version is released with the new pull requests.

**Comment by snicoll** [comment]
Not stuck no but no major changes are made to it either. The team is busy on other topics and reviewing large PRs can take quite some time.

**Comment by pedsf1968** [comment]
Closes #697, Closes #692

**Comment by dsyer** [comment]
#692 declined so this one should be closed too.

**Pull request closed without merging**
