### PR TITLE
Updating spacing on step list

### PR DESCRIPTION
**Pull request by ahatzz11**
Small PR to line up the bodies of each bullet point

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ahatzz11 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=587)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=587) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ahatzz11 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=587)!

**Comment by ahatzz11** [comment]
Hey @snicoll! Just thought I'd give a bump on this PR 😄

**Comment by ahatzz11** [comment]
@dsyer why was this closed?

**Comment by dsyer** [comment]
Mistake, sorry. I was experimenting with removing the "master" branch. Apparently this is a side effect (all outstanding PRs are automatically closed). :woman_shrugging:

**Comment by ahatzz11** [comment]
Interesting! I'm curious - why change from master to main?

**Comment by dsyer** [comment]
Some people find racist overtones in "master". If it's easy to change we think it's the right thing to do. Still experimenting (some automation might be needed).

**Comment by ahatzz11** [comment]
Ahh cool! I'd be interested to hear how the transition goes.

**Pull request merged**
