### PR TITLE
fix issue #138: Css issue with 'width'

### PR DESCRIPTION
**Pull request by lasiqueira**
Removed bootstrap2 theme from datatable since it was adding another
bootstrap.css

### CODE REVIEW

**Comment by arey** [comment]
@lasiqueira could you check if this issue is still there on the bootstrap3 branch? As you, I've removed the bootstrap3 theme from database?

**Comment by lasiqueira** [comment]
@arey There isn't anything in the /vendors/ folder, so it doesn't load any css and jquery...

**Comment by arey** [comment]
In order to download all vendors resources, you have to execute a ```mvn install```

**Comment by lasiqueira** [comment]
@arey I get this when I run mvn install:

Embedded error: Cannot run program "bower" (in directory "/home/luke/eclipse/jee-mars/eclipse/WS-petclinic/spring-petclinic"): error=2, No such file or directory

**Comment by arey** [comment]
Are you running ```mvn install``` from Eclipse or from a terminal?
If we cannot resolve this problem, I may commit the vendors files.

**Comment by lasiqueira** [comment]
@arey from a terminal. 

I was able to test it now that you have commited the vendors.

The CSS seems alright now!

**Pull request closed without merging**
