### PR TITLE
Update jenkins

### PR DESCRIPTION
**Pull request by JimLau49**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@JimLau49 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=541)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=541) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@JimLau49 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=541)!

**Comment by snicoll** [comment]
@JimLau49 can you check with the teacher if the instructions be amended please? We've had a number of unexpected PRs submitted here for this and this creates noise for no good reason.

**Comment by JimLau49** [comment]
Yeah for sure, ill send him an email. Sorry about the trouble we're causing :(

**Pull request closed without merging**
