### PR TITLE
Handling Null Pointer Exception for Owner ID

### PR DESCRIPTION
**Pull request by 4313testing**
handling null pointer Exception on Owner ID with IllegalArgumentException

### CODE REVIEW

**Comment by dsyer** [comment]
The result is the same for this and the code we already have. The only difference is the exception type, which doesn't show up in the web UI anyway, unless someone switches on error attributes includes manually. The logs in the server are slightly more verbose (messy) with the `DataAccessException`, but I think we'll live with it.

Also, the check for `<=0` was redundant.

**Comment by 4313testing** [comment]
it was your request to use IllegalArgumentException for the Null Pointer so i just did what you suggested

**Comment by dsyer** [comment]
Sorry, I think I closed the wrong one. I'll reopen and can you remove the `<=0` check since it isn't adding anything? Please rebase and squash into one commit.

**Comment by 4313testing** [comment]
okay i will do that

**Comment by 4313testing** [comment]
@dsyer sorry i had some conflicts in this branch 
i created a new PR #1294 
please check it

**Comment by dsyer** [comment]
I think you muffed it up somehow - I can see 4 commits and 0 files changed. I was expecting 1 commit and 1 file changed.

**Pull request closed without merging**
