### PR TITLE
Extend base functionality and add Rest controllers

### PR DESCRIPTION
**Pull request by vfedoriv**
**Proposed changes:**
_________________________________
1. Add new/extended interfaces:
PerRepository -> PetRepositoryExt (extends PerRepository)
(none) -  PetTypeRepositoryExt
etc...
2.  add implementation for this interfaces 
JdbcPetRepositoryExtImpl (implement PetRepositoryExt)
etc...
3. Add new service ClinicServiceExt (extends ClinicService) and implementation class
4. Add new package org.springframework.samples.petclinic.rest with REST controllers
5. Add tests for 1-4
________________________________
**Changes in old files:**
________________________________
1. Add @Qualifier annotation (for correct work @Autowired)
2. Add @JsonIdentityInfo for Pet (resolve infinite loop serialization)
3. Change Pet setOwner() method from protected to public
4. Change scope from private to protected in one JdbcVisitRepositoryImpl method
5. Add @NonEmpty constraint for "name" column in NamedEntity
_________________________________
**Not include / need extensions / discussed / etc...**
_________________________________
1. Proposed REST API "flat":
	/api/owners - GET/POST (get owners list/add new owner)
	/api/owners/1 - GET/PUT/DELETE (get/edit/delete owner)
	/api/pets
	/api/pettypes/
	etc...
"long" variant 
	/owners/{ownerId}/pets/{petId}/visits/ not implemented
2. Very simple exception handling in ExceptionControllerAdvice
	(just return stack trace in request body)
3. Realization delete() method - CASCADE 
	(if you delete owner, you delete all owner pets and owner pets visits)
4. Documentation

### CODE REVIEW

**Comment by arey** [comment]
Vitaliy, the legacy branch is moving to the spring-petclinic organization. The existing one will not be maintained. Thus we are not be able to merge your PR.
I suggest you to create a new repo called spring-rest-petclinic. You may remove the UI layer and focus on a beautiful REST API. You may start from the master branch of this repo (with Spring Boot and Spring Data JPA). What do you think about?

**Comment by vfedoriv** [comment]
Well, I see you create https://github.com/spring-petclinic/spring-framework-petclinic branch. Maybe just pull this changes there ?

**Comment by arey** [comment]
Vitaliy, I'm sorry but there are too many changes in your PR. Maybe some changes could be introduce in the spring-petclinic/spring-framework-petclinic. But your main changes are related to provide a REST API. By having both REST and UI controllers, Petclinic will become more complex. I believe that a Petclinic version without UI but just a REST API should be more suitable. 
For this new fork, we don't have to keep 3 persistances layers (only the Spring Data JPA) and I invite you to start from the master branch of the spring-projects/spring-petclinic.

**Comment by vfedoriv** [comment]
Yes, it can by splitted to core changes (maybe with creating additional packages like  .model.ext, .repository.ext etc...) and REST layer ( REST already in different package).
But at this time I don't see any benefit to fork branch from current master in spring-projects/spring-petclinic ( branch just in transition state) and work with this.
And after Dave finished all changes, Spring Data REST can be better solution in branch.

**Pull request closed without merging**
