### PR TITLE
Test using GitHub Actions

### PR DESCRIPTION
**Pull request by geertjanw**
Small contribution to the project, to enable testing on multiple JDK releases. Hope you like it!

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@geertjanw Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=660)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=660) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@geertjanw Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=660)!

**Comment by snicoll** [comment]
Thanks for the project but this project should remain as simple as possible and we don't need to test petclinic against multiple JDKs.

**Comment by geertjanw** [comment]
You don't need to test against multiple JDKs?

**Comment by snicoll** [comment]
This project is a sample app, not a library.

**Pull request closed without merging**
