### PR TITLE
Add missing gradle testcontainers dependencies

### LINKED ISSUE #1267: Gradle build lacks Testcontainers dependency
Following last week's addition of testcontainers https://github.com/spring-projects/spring-petclinic/commit/3c1ef72e6d45ef41fbc86f51476e5a72e9e66564 the Gradle build now fails with compilation errors due to a missing dependency there.
```
> Task :compileTestJava FAILED
/tmp/spring-petclinic/src/test/java/org/springframework/samples/petclinic/MySqlIntegrationTests.java:26: error: package org.springframework.boot.testcontainers.service.connection does not exist
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
                                                                 ^
/tmp/spring-petclinic/src/test/java/org/springframework/samples/petclinic/MySqlIntegrationTests.java:34: error: package org.testcontainers.containers does not exist
import org.testcontainers.containers.MySQLContainer;
                                    ^
...
```

It's likely that the same dependencies need to be added to `build.gradle`, such that it compiles and runs again.

I'd like to propose to also [add a Gradle build to the GitHub Actions workflows](https://github.com/spring-projects/spring-petclinic/tree/main/.github/workflows), such that it's tested in parallel.

### PR DESCRIPTION
**Pull request by letientai299**
CLoses #1267

### CODE REVIEW

**Comment by dsyer** [comment]
Looks good. Do you feel like adding the docker-compose dependency as well for the postgres integration tests?

**Comment by letientai299** [comment]
Unfortunately, I couldn't even run the `./gradlew test` or test in IDE successfully, so I can't work on the integration test further.

**Comment by dsyer** [comment]
You can't run it because the dependency is missing presumably? How did you get this far?

**Comment by letientai299** [comment]
I just follow the testcontainer docs to add those missing dependencies.

**Comment by dsyer** [comment]
Obsolete. See f85ad88.

**Pull request closed without merging**
