### PR TITLE
Upgrade for Spring Boot 3.1

### PR DESCRIPTION
**Pull request by patbaumgartner**
Upgrade to Spring Boot 3.1
- Updating Wrappers (Maven and Gradle)
- Removing Spring Java Format Config: Current default is at Java 11
- Updating PostgreSQL Docker Image
- Updating Plugin Version
- Adjusting Build-Info since `maven.compiler.source` and `maven.compiler.target` got removed from Spring Boot Parent because `maven.compiler.release` is already set.  #gh-34365
- Replacing by Pivotal with by VMware Tanzu (SVG).

### CODE REVIEW

**Comment by dsyer** [comment]
Could we extract the SVG into a separate file? It looks kind of ugly in line like that IMO.

**Comment by dsyer** [comment]
The spring.io website is a React.js app (I think) so any styles and logos that appear in thesite might be pre-processed during the build. I'm not sure I understand your suggestion to "add the styles into the SVG".

**Comment by dsyer** [comment]
You didn't want to use `th:src="@{...` ?

**Comment by patbaumgartner** [comment]
Well spotted @dsyer - Thank you for recognizing. I made it like all the other images.

**Pull request merged**
