### PR TITLE
Improved execution of grouped assertions

### PR DESCRIPTION
**Pull request by eas5**
**Problem:**
A test method with many individual assertions stops being executed on the first failed assertion, which prevents the remaining ones' execution.

**Solution:**
Using AssertJ soft assertions feature, all assertions are executed, and all failures will be reported together. In this refactoring, no original assertion was changed.

**Result:**
_Before:_
```
assertThat(owner.getLastName()).startsWith("Franklin");
assertThat(owner.getPets()).hasSize(1);
assertThat(owner.getPets().get(0).getType()).isNotNull();
assertThat(owner.getPets().get(0).getType().getName()).isEqualTo("cat");
```

_After:_
```
SoftAssertions softly = new SoftAssertions();
softly.assertThat(owner.getLastName()).startsWith("Franklin");
softly.assertThat(owner.getPets()).hasSize(1);
softly.assertThat(owner.getPets().get(0).getType()).isNotNull();
softly.assertThat(owner.getPets().get(0).getType().getName()).isEqualTo("cat");
softly.assertAll();
```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@eas5 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=742)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=742) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@eas5 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=742)!

**Comment by dsyer** [comment]
I'm fine with merging this if we can get it to work. And we prefer the assertj assertions, so thanks for that. Can you rebase again please?

Not sure what other opinions you are looking for.

**Comment by dsyer** [comment]
Sorry. Can you try that rebase again, please? It's difficult.

**Comment by eas5** [comment]
No problems for me to help the project with this CI issue through this PR.

Regarding the opinion I need, It is enough that you have agreed with the refactoring proposed in this PR. 

Thank you very much!

**Comment by dsyer** [comment]
I think you merged instead of rebasing. Can we get this change as one commit with one parent that is origin/main, please?

**Comment by eas5** [comment]
Unfortunately, I messed up with my local repo and this branch after merging and rebasing. I'm closing this PR to start a fresh new one. Thank you!

**Pull request closed without merging**
