### PR TITLE
Solucion Reto3 Robert

### PR DESCRIPTION
**Pull request by JRobertGutierrez**
La solución para el reto3 realizado por Roberto Gutiérrez.
Creadas las consultas insert, update y delete sin preparar y también con insert, update y delete preparadas.

### CODE REVIEW

**Comment by dsyer** [comment]
Spam?

**Comment by JRobertGutierrez** [comment]
> 
> 
> Spam?

Hi Dave, I am very sorry I did not answer before, but I am new to this and I did not know what to do exactly, I do not know pitvotal cla, I just did a pullrequest of a project in which we are several students practicing spring, but I did not know anything. being a lot of truth, if you tell me what steps I have to follow I can try it, thank you very much. All the best.

**Comment by dsyer** [comment]
The CLA is just a form you fill in (link above). You only need to do it once for all Spring projects. So go ahead and do it if you are interested in contributing. This PR doesn’t look very interesting to this project to me, and we get a lot of these “just practicing” requests, that aren’t really all that serious. But if you want you can explain what the change is, and why you would like to see it.

**Comment by JRobertGutierrez** [comment]
> 
> 
> The CLA is just a form you fill in (link above). You only need to do it once for all Spring projects. So go ahead and do it if you are interested in contributing. This PR doesn’t look very interesting to this project to me, and we get a lot of these “just practicing” requests, that aren’t really all that serious. But if you want you can explain what the change is, and why you would like to see it.

Hi Dave, when I get more experience in application development I will start to contribute, for now they are just learning practices, thank you very much anyway. All the best.

**Pull request closed without merging**
